config/routes.rb
Rails.application.routes.draw do
  get 'visits/create'
  get 'visits/destroy'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  get 'spots/index'
  get 'spots/show'
  get 'spots/new'
  get 'spots/create'
  get 'spots/edit'
  get 'spots/upload'
  get 'spots/destroy'
  get 'users/index'
  get 'users/show'
  get 'users/new'
  get 'users/create'
  get 'users/edit'
  get 'users/upload'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    
    root to: 'users#index'
    
    get 'login' ,to:'sessions#new'
    post 'login' ,to:'sessions#create'
    delete 'logout', to:'sessions#destroy'
    
    get 'signup', to:'user#new'
    
    post 'update', to:'user#update'
    resources:users do
      
      post :confirm, action: :confirm_new, on: :new
      member do 
        get :visits
        get :visited
      end
    end
    
 
    resources:spots do
      collection do
        get :search
      end
    end
    resources:visits , only: [:create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/spot.rb
class Spot < ApplicationRecord
    mount_uploader :image, ImageUploader
    belongs_to :user
    
    validates :prefecture, presence: true
    validates :city, presence: true
    validates :name, presence: true, length: {maximum:30}
    validates :content, presence: true, length: { maximum: 255}
   
    
    has_many :reverses_of_visits,class_name: 'Visit',foreign_key:'user_id'
    has_many :liked, through: :reverses_of_visits, source: :user
    
      def self.search(search)
        return Spot.all unless search
        Spot.where(['CONCAT(name,prefecture) Like?',"%#{search}%"])

      end
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email.downcase!}
    validates :name, presence: true, length: { maximum: 50}
    validates :email, presence: true, length: { maximum: 255},
            format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
 
    has_secure_password
    has_many :spots
    has_many :visits
    has_many :likes,through: :visits, source: :spot
    
    
    def like(other_spot)
        self.visits.find_or_create_by(spot_id: other_spot.id)
    end
    
    def unlike(other_spot)
        visit = self.visits.find_by(spot_id: other_spot.id)
        visit.destroy if visit
    end
    
    def visited?(other_spot)
        self.likes.include?(other_spot)
    end
    
    def feed_spots
        Spot.where(spot_id: self.like_ids)
    end
    
end

app/models/visit.rb
class Visit < ApplicationRecord
  belongs_to :user
  belongs_to :spot
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
    
    def require_user_logged_in
        unless logged_in?
          redirect_to login_url
        end
    end
    
    def counts(user)
        @counts_visit_spots = user.visits.count
        

        @counts_visit_osaka = user.likes.where(prefecture: '大阪').count
        @counts_visit_hyogo = user.likes.where(prefecture: '兵庫').count
        @counts_visit_nara = user.likes.where(prefecture: '奈良').count
        @counts_visit_kyoto = user.likes.where(prefecture: '京都').count
       

    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email,password)
      flash[:success] = "ログインしました"
      redirect_to @user
    else
      flash.now[:danger] ="ログインできませんでした"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] ="ログアウト"
    redirect_to root_url
  end
  
  def login(email,password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  # mount_uploader :image, ImageUploader
  before_action :require_user_logged_in, only: [:new, :edit, :destroy]
  include SessionsHelper
  def index
    @spots = Spot.order(id: :desc).page(params[:page]).per(10)
    @query = Spot.ransack(params[:q])
    @articles = @query.result(distinct: true)
  end

  def show
      @spot = Spot.find(params[:id])
  end

  def new
    @spot = Spot.new
  end

  def create
    @spot = current_user.spots.build(spots_params)
    if @spot.save
      flash[:success] = '投稿しました'
      redirect_to :users_show
    else
      flash[:danger] = '修正してください'
      render 'spots/new'
    end
  end

  def edit
    @spot = Spot.find(params[:id])
  end

  def update
    @spot = Spot.find(params[:id])
    
    if @spot.update(spots_params)
      flash[:success] = '変更されました'
      redirect_to @spot
    else
      flash[:danger] = '変更できませんでした'
      render :edit
    end
  end

  def destroy
    @spot = Spot.find(params[:id])
    
    if @spot.destroy
      flash[:success] ='投稿を削除しました'
      redirect_to spot_url
    else
      
    end
  end
  
  def search
    @posts = Spot.search(params[:search]).page(params[:page])
    @post = params[:search]
  end

  
  private
  def spots_params
    params.require(:spot).permit(:prefecture,:city,:name,:content,:image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :require_user_logged_in, only: [:show, :edit]
  include SessionsHelper
  def index

  end

  def show
    @user = User.find(current_user.id)
    @spots = @user.spots.order(id: :desc).page(params[:page])
    counts(@user)
    @visits = current_user.likes.order(id: :desc).page(params[:page])
    #@all_ranks = @visits.find(Spot.group(:prefecture).order('count(prefecture) desc').limit(3).pluck(:prefecture))
    @all_ranks = current_user.likes.group(:prefecture).order('count(prefecture) desc').limit(3).pluck(:prefecture)
  end

  def new
    @user = User.new
  end
  
  def confirm_new
    @user = User.new(user_params)
    unless @user.valid?
      render :new 
      flash[:danger] = '入力内容に謝りがあります。'
    end
  end

  def create
    @user = User.new(user_params)
    if params[:back].present?
      render :new
      return
    end
    if @user.save
      flash[:success] = "ユーザー登録しました"
      redirect_to login_path
    else
      flash[:danger] = "ユーザー登録失敗しました"
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def upldate
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)  
  end
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  before_action :require_user_logged_in
  
  def create
    spot = Spot.find(params[:spot_id])
    current_user.like(spot)
    flash[:success] = "訪問済みにしました"
    redirect_to spot
  end

  def destroy
    spot = Spot.find(params[:spot_id])
    current_user.unlike(spot)
    flash[:danger] ="訪問済みを取り消しました"
    redirect_to spot
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def default_meta_tags
        {
            title: "本当に行きたい、行ったことがない場所が見つかる | siori",
            description: "自分の行った行き先を投稿し、他人の投稿のなかで、行ったことのある場所をチェックすると行ったことのない場所がわかるようになります。",
            keywords: "観光,旅行,旅,大阪,京都,兵庫,奈良,日帰り",
            canonical: request.original_url,
            carset: "UTF-8",
            
            og: {
                title: "行ったことのない穴場が見つかる",
                description: :description,
                type: "website",
                url: request.original_url,
                site_name: "siori",
                locale: "ja_JP",
            },
        }
        
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper
    
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
    
    def logged_in?
        !!current_user
    end
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %> mt-3"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-light bg-light" id="nav">
    <%= link_to 'siori', root_path ,class: 'navbar-brand' %>
    
    
    <% if logged_in? %>
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#nav-bar">
           <span class="navbar-toggler-icon"></span> 
        </button>
        <div class="collapse navbar-collapse" id="nav-bar">
            <ul class="navbar-nav">
                <li class="nav-item"><%= link_to '探す', spots_path ,class: 'nav-link' %></li>
                <li class="nav-item"><%= link_to current_user.name , users_show_path ,class: 'nav-link'%></li>
                <li class="nav-item"><%= link_to 'ログアウト',logout_path ,method: :delete,class: 'nav-link'%></li>
            </ul>
        </div>
    <% else %>
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#nav-bar">
           <span class="navbar-toggler-icon"></span> 
        </button>
        <div class="collapse navbar-collapse" id="nav-bar">
            <ul class="navbar-nav">
                <li class="nav-item"><%= link_to '探す', spots_path ,class: 'nav-link' %></li>
                <li class="nav-item"><%= link_to '会員登録', users_new_path ,class: 'nav-link'%></li>
                <li class="nav-item"><%= link_to 'ログイン',login_path ,class: 'nav-link'%></li>
            </ul>
        </div>
    <% end %>
</nav>

app/views/layouts/_visited_button.html.erb
    <% if current_user.visited?(spot) %>
    
        <%= form_with(model: current_user.visits.find_by(spot_id: spot.id),local: true, method: :delete) do |f| %>
        <%= hidden_field_tag :spot_id, spot.id %> 
        <%= f.submit 'unvisit', class: 'btn btn-primary' %>
        <% end %>
    <% else %>
        <%= form_with(model: current_user.visits.build, local: true) do |f| %>
        <%= hidden_field_tag :spot_id, spot.id %>
        <%= f.submit 'visited!', class: 'btn btn-danger' %>
        <% end %>
        
    <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio2</title>
    
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= display_meta_tags(default_meta_tags) %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/cf894b39db.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </head>

  <body>
  
    <%= render 'layouts/navbar' %>
    <div class="pt-5">
       <%= render 'layouts/flash' %>
    <%= yield %>   
    </div>

    
    
  </body>
</html>

app/views/spots/edit.html.erb
<% set_meta_tags noindex: true%>



<div class="container">

    
    <div class="row">
      <div class="col-sm-6 offset-sm-3">
        <h2>編集画面</h2>
        <%= form_with(model: @spot, local: true) do |f| %>
          
          <div class="form-group">
            <%= f.label :prefecture, '都道府県' %>
            <%= f.select :prefecture, [["大阪","大阪"],["兵庫","兵庫"],["京都","京都"],["奈良","奈良"]],class: 'form-control' %>
          </div>
    
          <div class="form-group">
            <%= f.label :city, '市区町村' %>
            <%= f.text_field :city, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :adress, '住所' %>
            <%= f.text_field :adress, class: 'form-control' %>
          </div>
    
          <div class="form-group">
            <%= f.label :name, '名称' %>
            <%= f.text_field  :name, class: 'form-control' %>
          </div>
    
          <div class="form-group">
            <%= f.label :content, '紹介' %>
            <%= f.text_field  :content, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :image, 'イメージ画像' %><br>
            <%= f.file_field :image %>
          </div>
    
          <%= f.submit '編集完了', class: 'btn btn-primary btn-block' %>
        <% end %>
      </div>
    </div>
</div>

app/views/spots/index.html.erb
<div class="spot_conA pt-3">
    <div class="form-group">
        <%= form_with url: search_spots_path,method: :get,local: true do |f| %>
        <%= f.text_field :search, class: 'form-control',placeholder:'都道府県 観光地名' %>
        <%= f.submit '検索',class: "btn btn-info btn-s-md mt-1"%>
        
      
    <% end %>
    </div>

    <div class="spot_index_content">
          <ul>
                <% @spots.each do |spot| %>
                <li>
                      <div class="spot_index_spot_content">
                         <div class="spot_index_spot_contentA">
                            <% if spot.image? %>
                                <%= image_tag (spot.image_url),class: 'img' %>
                            <% else %>
                                <span class="fas fa-camera icon"></span> <!-- using a <span> element to reference the icon -->
                            <% end %>
                        </div>
                        <div class="spot_index_spot_contentB">
                            <p><%= spot.name %><br><%= link_to '詳細', spot_path(spot) %></p> 
                        </div>
                     </div>    
                </li>
                <% end %>
            </ul>

    </div>
</div>

app/views/spots/new.html.erb
<% set_meta_tags noindex: true%>

<div class="container">

    
    <div class="row">
      <div class="col-sm-6 offset-sm-3">
    
        <%= form_with(model: @spot, local: true) do |f| %>
          
          <div class="form-group">
            <%= f.label :prefecture, '都道府県' %>
            <%= f.select :prefecture, [["大阪","大阪"],["兵庫","兵庫"],["京都","京都"],["奈良","奈良"]], class: 'form-control' %>
          </div>
    
          <div class="form-group">
            <%= f.label :city, '市区町村' %>
            <%= f.text_field :city, class: 'form-control' %>
          </div>          
          <div class="form-group">
            <%= f.label :adress, '住所' %>
            <%= f.text_field :adress, class: 'form-control' %>
          </div>
    
          <div class="form-group">
            <%= f.label :name, '名称' %>
            <%= f.text_field  :name, class: 'form-control' %>
          </div>
    
          <div class="form-group">
            <%= f.label :content, '紹介' %>
            <%= f.text_field  :content, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :image, 'イメージ画像' %><br>
            <%= f.file_field :image %>
          </div>
    
          <%= f.submit '投稿する', class: 'btn btn-primary btn-block' %>
        <% end %>
      </div>
    </div>
</div>

app/views/spots/search.html.erb
<div class="spot_conA pt-3">
    <div class="search_content">
        <%= form_with url: search_spots_path,method: :get,local: true do |f| %>
        <%= f.text_field :search, class: 'form-control',placeholder:'都道府県 観光地名' %>
        <%= f.submit '検索',class: "btn btn-info btn-s-md mt-1 mb-3"%>
        
      
        <% end %>
    </div>

    <div class="spot_index_content">
        検索結果：<%= @post %>

          <ul>
                <% @posts.each do |spot| %>
                <li>
                      <div class="spot_index_spot_content">
                         <div class="spot_index_spot_contentA">
                            <% if spot.image? %>
                                <%= image_tag (spot.image_url),class: 'img' %>
                            <% else %>
                                <span class="fas fa-camera icon"></span> <!-- using a <span> element to reference the icon -->
                            <% end %>
                        </div>
                        <div class="spot_index_spot_contentB">
                            <p><%= spot.name %><br><%= link_to '詳細', spot_path(spot) %></p> 
                        </div>
                     </div>    
                </li>
                <% end %>
            </ul>
        


        

    </div>
</div>

app/views/spots/show.html.erb
<div class="container">
    <div class="spot_content">

        <h1><%= @spot.name %></h1>
        
        <% if logged_in? %>
        <%= render 'layouts/visited_button', spot: @spot %>
        <% end %>
        
        <% if @spot.image? %>
            <div class="spot_content_img">
                    <%= image_tag @spot.image.url %>
            </div>

        <% else %>
         <i class="far fa-images"></i>
        <% end %>
   
           <table class="table table-bordered">
            <tr>

                <td><%= @spot.content%></td>
            </tr>

        </table>
     <h2>観光地情報</h2>
        <table class="table table-bordered">
            <tr>

                <td>名称:<%= @spot.name %></td>
                <td>名称:<%= @spot.prefecture %></td>
            </tr>
            <tr>

                <td>住所:<%= @spot.adress %></td>
            </tr>
        </table>
        <!--地図表示させる-->
        <% if logged_in? %>
        <% render 'layouts/visited_button', spot: @spot %>
        <% end %>
        
        <% if current_user == @spot.user %>
        <%= link_to '編集する', edit_spot_path(@spot) %>
        <%= link_to '削除', @spot, method: :delete, data: {confirm: '削除してよろしいですか？'} %>
        <% end %>
    </div>


    
    
</div>

app/views/users/confirm_new.html.erb
<div class="container">
    <div>
    <h1>登録内容の確認</h1>
    </div>
    <div class="row">
        <%= form_with(model: @user, local: true) do |f| %>
        <table class="table table-hover">
            <tr>
                <th>名前</th>
                <td><%= f.hidden_field :name %><%= @user.name %></td>
            </tr>
            <tr>
                <th>email</th>
                <td><%= f.hidden_field :email %><%= @user.email %></td>
            </tr>
            
            <tr>
                <th>パスワード</th>
                <td><%= f.hidden_field :password %><%= @user.password %></td>
            </tr>
            
            <tr>
                <th>確認</th>
                <td><%= f.hidden_field :password_confirmation %><%= @user.password_confirmation %></td>
            </tr>
        
            </table>
            
        <%= f.submit '戻る',name:'back', class: 'btn btn-secondary btn-block' %>
        <%= f.submit '登録', class: 'btn btn-primary btn-block' %>
        <% end %>
    </div>
</div>

app/views/users/edit.html.erb
<div class="container">
    <div class="text-center">
      <h1>マイページ編集</h1>
    </div>
    
    <div class="row">
      <div class="col-sm-6 offset-sm-3">
    
        <%= form_with(model: @user, local: true) do |f| %>
          
          <div class="form-group">
            <%= f.label :name, 'Name' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
    
          <div class="form-group">
            <%= f.label :email, 'Email' %>
            <%= f.email_field :email, class: 'form-control' %>
          </div>
    
          <%= f.submit '登録する', class: 'btn btn-primary btn-block' %>
        <% end %>
      </div>
    </div>
</div>

app/views/users/index.html.erb
<div class="user_conA">
    
    <div class="offset-sm-4 col-sm-3 top ">
        <div class="main-content">
        <p class="text-centet">観光地を検索</p>
        <%= form_with url: search_spots_path,method: :get,local: true do |f| %>
        <%= f.text_field :search, class: 'form-control',placeholder:'都道府県 観光地名' %>
        <%= f.submit '検索',class: "btn btn-info btn-s-md mt-1 btn-block"%>
        <% end %>
                    
        </div>
    </div>
</div>

app/views/users/new.html.erb
<div class="container">
    <div class="text-center">
      <h1>Sign up</h1>
    </div>
    
    <div class="row">
      <div class="col-sm-6 offset-sm-3">
    
        <%= form_with(model: @user, local: true, url: confirm_new_user_path) do |f| %>
          
          <div class="form-group">
            <%= f.label :name, 'Name' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
    
          <div class="form-group">
            <%= f.label :email, 'Email' %>
            <%= f.email_field :email, class: 'form-control' %>
          </div>
    
          <div class="form-group">
            <%= f.label :password, 'Password' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>
    
          <div class="form-group">
            <%= f.label :password_confirmation, 'Confirmation' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>
    
          <%= f.submit '確認', class: 'btn btn-primary btn-block' %>
        <% end %>
      </div>
    </div>
</div>

app/views/users/show.html.erb
<div class="user_show_conA">
    

    <div class="user_show_conC">
 
        
        <div class="user_show_leftcon">
            <div>
                <h1>プロフィール</h1>
            </div>
            <table>
                <tr>
                    <th>氏名</th>
                    <td><%= @user.name%></td>
                </tr>
                <tr>
                    
                </tr>
            </table>
    
            <div>
                <%= link_to '投稿',spots_new_path,class:'btn btn-primary btn_post' %>
                <%= link_to 'マイページ編集',edit_user_path(@user) %>
        
            </div>
            <table class="table">
                <tr>
                    <th>あなたの投稿</th>
                </tr>
                <% @spots.each do |spot| %>
                    <tr>
                        <td><%= spot.name %><%= link_to '詳細', spot %></td>
                    </tr>
                <% end %>
            </table>
        </div>
    </div>
    <div class="user_show_conB">

        <div>

            <h2>訪問済みスポット</h2>
                <p>総合：<%= @counts_visit_spots %></p>
                <p>大阪：<%= @counts_visit_osaka %></p>
                <p>兵庫：<%= @counts_visit_hyogo %></p>
                <p>奈良：<%= @counts_visit_nara %></p>
                <p>京都：<%= @counts_visit_kyoto%></p>
                <span></span>
                
            <h2>よく行く地域は...</h2>
            <% @all_ranks.each.with_index(1) do |spot, i| %>
            <p><%= i %>位:<%= spot.presence %></p>
    
            <% end %>
        </div>
        <div class="user_show_myspot">
            <h2>訪問済み</h2>

            <ul>
                <% @visits.each do |visit| %>
               
                <li>
                    <div class="user_show_myspot_content">
                        
                   
                        <div class="user_show_myspot_contentA">
                            <% if visit.image? %>
                            <%= image_tag (visit.image_url),class: 'img' %>
                        <% else %>
                            <span class="fas fa-camera icon"></span> <!-- using a <span> element to reference the icon -->
                        <% end %>
                        </div>

                        <div class="user_show_myspot_contentB">
                            <h3><%= visit.name%></h3>
                            <p><%= visit.prefecture %></p>
                            <p><%= visit.adress %></p>
                            <p><%= link_to '詳細', spot_path(visit) %></p> 
                            <p><%= visit.user.name %></p>
                        </div>
                     </div>    
                </li>

                <% end %>
                
            </ul>

            
        </div>

    </div>
</div>

app/views/visits/create.html.erb
<h1>Visits#create</h1>
<p>Find me in app/views/visits/create.html.erb</p>

app/views/visits/destroy.html.erb
<h1>Visits#destroy</h1>
<p>Find me in app/views/visits/destroy.html.erb</p>